version: "3.9"

networks:
  microservices-net:
    driver: bridge

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Zoubair@123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    expose:
      - "1433"
    networks:
      - microservices-net
    restart: unless-stopped
    
  auth-service:
    image: ghcr.io/zoubairmabrouk/auth-service:${AUTH_VERSION}
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;Database=AuthDb;
        User Id=sa;Password=Zoubair@123;TrustServerCertificate=True
      Jwt__SecretKey:                "qsjhdhqsdhhuzhdhdgeudgudsgv,nfkuhzgezfuvjhknfjhsdbgvsqjhvvudsdfhvfuzbhjdqsjbddahugfu"
      Jwt__Issuer:                   "auth-service"
      Jwt__Audience:                 "microservices"
      Jwt__AccessTokenExpiryMinutes: "15"
      Jwt__RefreshTokenExpiryDays:   "7"
    networks:
      - microservices-net
    depends_on:
      - sqlserver
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5

  mdx-service:
    image: ghcr.io/zoubairmabrouk/mdx-service:${MDX_VERSION}
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;Database=MdxDb;
        User Id=sa;Password=Zoubair@123;TrustServerCertificate=True
      Jwt__SecretKey: "qsjhdhqsdhhuzhdhdgeudgudsgv,nfkuhzgezfuvjhknfjhsdbgvsqjhvvudsdfhvfuzbhjdqsjbddahugfu"
      Jwt__Issuer:    "auth-service"
      Jwt__Audience:  "microservices"
    networks:
      - microservices-net
    depends_on:
      - sqlserver
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5

  rag-service:
    image: ghcr.io/zoubairmabrouk/rag-service:${AI_VERSION}
    expose:
      - "8000"
    environment:
      JWT_SECRET_KEY: "qsjhdhqsdhhuzhdhdgeudgudsgv,nfkuhzgezfuvjhknfjhsdbgvsqjhvvudsdfhvfuzbhjdqsjbddahugfu"
      JWT_ISSUER:     "auth-service"
      JWT_AUDIENCE:   "microservices"
    networks:
      - microservices-net
    restart: unless-stopped

  gateway:
    image: ghcr.io/zoubairmabrouk/gateway-service:${GATEWAY_VERSION}
    ports:
      - "8090:8080"           # seul port exposé vers l'extérieur
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__SecretKey: "qsjhdhqsdhhuzhdhdgeudgudsgv,nfkuhzgezfuvjhknfjhsdbgvsqjhvvudsdfhvfuzbhjdqsjbddahugfu"
      Jwt__Issuer:    "auth-service"
      Jwt__Audience:  "microservices"
    networks:
      - microservices-net
    depends_on:
      - auth-service
      - mdx-service
      - rag-service
    restart: unless-stopped
  conv-service:
    image: ghcr.io/zoubairmabrouk/conv-service:${CONV_VERSION}
    expose:
      - "8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;Database=ConvDb;
        User Id=sa;Password=Zoubair@123;TrustServerCertificate=True
      Jwt__SecretKey: "qsjhdhqsdhhuzhdhdgeudgudsgv,nfkuhzgezfuvjhknfjhsdbgvsqjhvvudsdfhvfuzbhjdqsjbddahugfu"
      Jwt__Issuer:    "auth-service"
      Jwt__Audience:  "microservices"
    networks:
      - microservices-net
    depends_on:
      - sqlserver
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5

volumes:
  sqlserver-data: